/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as LayoutImport } from "./routes/_layout"
import { Route as LayoutIndexImport } from "./routes/_layout/index"
import { Route as LayoutHotelsCitySlugIndexImport } from "./routes/_layout/hotels/$citySlug/index"
import { Route as LayoutHotelsCitySlugHotelSlugImport } from "./routes/_layout/hotels/$citySlug/$hotelSlug"

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: "/_layout",
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHotelsCitySlugIndexRoute = LayoutHotelsCitySlugIndexImport.update({
  id: "/hotels/$citySlug/",
  path: "/hotels/$citySlug/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHotelsCitySlugHotelSlugRoute =
  LayoutHotelsCitySlugHotelSlugImport.update({
    id: "/hotels/$citySlug/$hotelSlug",
    path: "/hotels/$citySlug/$hotelSlug",
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/hotels/$citySlug/$hotelSlug": {
      id: "/_layout/hotels/$citySlug/$hotelSlug"
      path: "/hotels/$citySlug/$hotelSlug"
      fullPath: "/hotels/$citySlug/$hotelSlug"
      preLoaderRoute: typeof LayoutHotelsCitySlugHotelSlugImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/hotels/$citySlug/": {
      id: "/_layout/hotels/$citySlug/"
      path: "/hotels/$citySlug"
      fullPath: "/hotels/$citySlug"
      preLoaderRoute: typeof LayoutHotelsCitySlugIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutHotelsCitySlugHotelSlugRoute: typeof LayoutHotelsCitySlugHotelSlugRoute
  LayoutHotelsCitySlugIndexRoute: typeof LayoutHotelsCitySlugIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutHotelsCitySlugHotelSlugRoute: LayoutHotelsCitySlugHotelSlugRoute,
  LayoutHotelsCitySlugIndexRoute: LayoutHotelsCitySlugIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  "": typeof LayoutRouteWithChildren
  "/": typeof LayoutIndexRoute
  "/hotels/$citySlug/$hotelSlug": typeof LayoutHotelsCitySlugHotelSlugRoute
  "/hotels/$citySlug": typeof LayoutHotelsCitySlugIndexRoute
}

export interface FileRoutesByTo {
  "/": typeof LayoutIndexRoute
  "/hotels/$citySlug/$hotelSlug": typeof LayoutHotelsCitySlugHotelSlugRoute
  "/hotels/$citySlug": typeof LayoutHotelsCitySlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/_layout": typeof LayoutRouteWithChildren
  "/_layout/": typeof LayoutIndexRoute
  "/_layout/hotels/$citySlug/$hotelSlug": typeof LayoutHotelsCitySlugHotelSlugRoute
  "/_layout/hotels/$citySlug/": typeof LayoutHotelsCitySlugIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "" | "/" | "/hotels/$citySlug/$hotelSlug" | "/hotels/$citySlug"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/hotels/$citySlug/$hotelSlug" | "/hotels/$citySlug"
  id:
    | "__root__"
    | "/_layout"
    | "/_layout/"
    | "/_layout/hotels/$citySlug/$hotelSlug"
    | "/_layout/hotels/$citySlug/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/hotels/$citySlug/$hotelSlug",
        "/_layout/hotels/$citySlug/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/hotels/$citySlug/$hotelSlug": {
      "filePath": "_layout/hotels/$citySlug/$hotelSlug.tsx",
      "parent": "/_layout"
    },
    "/_layout/hotels/$citySlug/": {
      "filePath": "_layout/hotels/$citySlug/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
